### ISSUE TITLE
pulsetile initialisation-not working with -qewd hit platform 

### ISSUE THREAD

**Issue by tony-shannon** [PulseTile/PulseTile-RA-Lerna#8]
thanks to  @kevinoflanagan for help documenting this in advance

**Comment by kevinoflanagan** [comment]
After successful project compilation via npm start, the browser opens to {Host}:3000/#/login with the spinner image and accompanying tip message. However, the fetch request to http://{host}:8080/api/initialise fails with a Bad Request error causing the project to remain on this page and does not redirect to the login screen. 

This error only appears to occur when using qewd-hit-platform; only being rectified by returning to QEWD-Courier.

**Comment by kevinoflanagan** [comment]
Issue resolved using NGINX configuration as per latest commit of qewd-hit-platform to map PulseTile REST calls to HIT Platform. 

@tony-shannon Please consider this resolved for issue closure. Thank you.
